### ISSUE TITLE
Thread safety issue with rest-client possibly

### ISSUE THREAD

**Issue by majksner** [mailgun/mailgun-ruby#208]
Hi,

I know this is not issue with the Mailgun gem itself (it's rest-client and then socksify which are dependancies), but when I try to send a newsletter to let's say 5000 people, Sidekiq gets stuck around every 25 to 50 API calls and then Sidekiq hangs for a minute or two without doing anything. I've tried to debug it and this is what Sidekiq produces with TTIN signal (based on https://github.com/mperham/sidekiq/wiki/Signals)

If I switch to smtp sending it getting stuck often but improves little bit, I'm also getting a lot of:

```
Net::OpenTimeout
execution expired
```

I've tried both 587 and 2525 ports.

Anyone else experiencing this issue, are there any way to tackle this?

```
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: 2020-06-23T13:52:55.479Z pid=19122 tid=2c6 WARN: Thread TID-2cua processor
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: 2020-06-23T13:52:55.479Z pid=19122 tid=2c6 WARN: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/socksify-1.7.1/lib/socksify.rb:178:in `initialize'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/socksify-1.7.1/lib/socksify.rb:178:in `initialize'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /home/deploy/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/net/http.rb:960:in `open'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /home/deploy/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/net/http.rb:960:in `block in connect'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /home/deploy/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/timeout.rb:78:in `timeout'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /home/deploy/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/net/http.rb:958:in `connect'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /home/deploy/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/net/http.rb:943:in `do_start'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /home/deploy/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/net/http.rb:932:in `start'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/rest-client-2.0.2/lib/restclient/request.rb:715:in `transmit'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/rest-client-2.0.2/lib/restclient/request.rb:145:in `execute'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `execute'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/rest-client-2.0.2/lib/restclient/resource.rb:67:in `post'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/mailgun-ruby-1.2.0/lib/mailgun/client.rb:104:in `post'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/mailgun-ruby-1.2.0/lib/mailgun/client.rb:87:in `send_message'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/mailgun-ruby-1.2.0/lib/railgun/mailer.rb:49:in `deliver!'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/mail-2.7.1/lib/mail/message.rb:2159:in `do_delivery'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/mail-2.7.1/lib/mail/message.rb:260:in `block in deliver'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/actionmailer-6.0.3.2/lib/action_mailer/base.rb:589:in `block in deliver_mail'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/notifications.rb:180:in `block in instrument'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/notifications.rb:180:in `instrument'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/actionmailer-6.0.3.2/lib/action_mailer/base.rb:587:in `deliver_mail'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/mail-2.7.1/lib/mail/message.rb:260:in `deliver'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/actionmailer-6.0.3.2/lib/action_mailer/message_delivery.rb:115:in `block in deliver_now'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/actionmailer-6.0.3.2/lib/action_mailer/rescuable.rb:17:in `handle_exceptions'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/actionmailer-6.0.3.2/lib/action_mailer/message_delivery.rb:114:in `deliver_now'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/actionmailer-6.0.3.2/lib/action_mailer/mail_delivery_job.rb:23:in `perform'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/activejob-6.0.3.2/lib/active_job/execution.rb:40:in `block in perform_now'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:112:in `block in run_callbacks'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/sentry-raven-3.0.0/lib/raven/integrations/rails/active_job.rb:13:in `block (2 levels) in included'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:121:in `instance_exec'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/i18n-1.8.3/lib/i18n.rb:313:in `with_locale'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/activejob-6.0.3.2/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:121:in `instance_exec'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/activejob-6.0.3.2/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:121:in `instance_exec'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/activejob-6.0.3.2/lib/active_job/logging.rb:25:in `block (4 levels) in <module:Logging>'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/notifications.rb:180:in `block in instrument'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/notifications.rb:180:in `instrument'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/activejob-6.0.3.2/lib/active_job/logging.rb:24:in `block (3 levels) in <module:Logging>'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/activejob-6.0.3.2/lib/active_job/logging.rb:45:in `block in tag_logger'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/tagged_logging.rb:80:in `block in tagged'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/tagged_logging.rb:28:in `tagged'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/tagged_logging.rb:80:in `tagged'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/activejob-6.0.3.2/lib/active_job/logging.rb:45:in `tag_logger'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/activejob-6.0.3.2/lib/active_job/logging.rb:21:in `block (2 levels) in <module:Logging>'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:121:in `instance_exec'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:139:in `run_callbacks'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/activejob-6.0.3.2/lib/active_job/execution.rb:39:in `perform_now'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/activejob-6.0.3.2/lib/active_job/execution.rb:25:in `block in execute'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:112:in `block in run_callbacks'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/activejob-6.0.3.2/lib/active_job/railtie.rb:43:in `block (4 levels) in <class:Railtie>'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/execution_wrapper.rb:88:in `wrap'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/reloader.rb:72:in `block in wrap'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/execution_wrapper.rb:84:in `wrap'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/reloader.rb:71:in `wrap'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/activejob-6.0.3.2/lib/active_job/railtie.rb:42:in `block (3 levels) in <class:Railtie>'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:121:in `instance_exec'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:139:in `run_callbacks'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/activejob-6.0.3.2/lib/active_job/execution.rb:23:in `execute'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/activejob-6.0.3.2/lib/active_job/queue_adapters/sidekiq_adapter.rb:42:in `perform'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:196:in `execute_job'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:164:in `block (2 levels) in process'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/sidekiq-6.0.7/lib/sidekiq/middleware/chain.rb:138:in `block in invoke'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/ros-apartment-sidekiq-1.2.0/lib/apartment/sidekiq/middleware/server.rb:5:in `block in call'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/ros-apartment-2.6.1/lib/apartment/adapters/abstract_adapter.rb:90:in `switch'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /home/deploy/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/forwardable.rb:235:in `switch'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/ros-apartment-sidekiq-1.2.0/lib/apartment/sidekiq/middleware/server.rb:4:in `call'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/sidekiq-6.0.7/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/sidekiq-unique-jobs-7.0.0.beta20/lib/sidekiq_unique_jobs/middleware.rb:81:in `call'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/sidekiq-6.0.7/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/sentry-raven-3.0.0/lib/raven/integrations/sidekiq.rb:9:in `call'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/sidekiq-6.0.7/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/sidekiq-6.0.7/lib/sidekiq/middleware/chain.rb:143:in `invoke'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:163:in `block in process'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/sidekiq-6.0.7/lib/sidekiq/job_retry.rb:111:in `local'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/sidekiq-6.0.7/lib/sidekiq/rails.rb:43:in `block in call'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/execution_wrapper.rb:88:in `wrap'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/reloader.rb:72:in `block in wrap'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/execution_wrapper.rb:88:in `wrap'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/reloader.rb:71:in `wrap'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/sidekiq-6.0.7/lib/sidekiq/rails.rb:42:in `call'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:257:in `stats'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/sidekiq-6.0.7/lib/sidekiq/job_logger.rb:13:in `call'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/sidekiq-6.0.7/lib/sidekiq/job_retry.rb:78:in `global'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:124:in `block in dispatch'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/sidekiq-6.0.7/lib/sidekiq/logger.rb:10:in `with'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/sidekiq-6.0.7/lib/sidekiq/job_logger.rb:33:in `prepare'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:123:in `dispatch'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:162:in `process'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:78:in `process_one'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:68:in `run'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/sidekiq-6.0.7/lib/sidekiq/util.rb:15:in `watchdog'
Jun 23 13:52:55 myapp-app sidekiq-myapp[19122]: /var/www/myapp/shared/bundle/ruby/2.7.0/gems/sidekiq-6.0.7/lib/sidekiq/util.rb:24:in `block in safe_thread'
```

Rails: Latest
Ruby: Latest
Sidekiq: Latest
Mailgun-Ruby: Latest

Thanks,

**Comment by Retttro** [comment]
@majksner Is this still an issue for you with the 1.2.4 gem version? I've tried to reproduce the issue but didn't have success. I'd suggest trying the batch message functionality if it matches your requirements.

**Comment by majksner** [comment]
I cannot try it, as I switched to https://github.com/aws/aws-sdk-rails for newsletters, and I use Mailgun only for transactional emails.

**Comment by zeefarmer** [comment]
Cannot reproduce
