### ISSUE TITLE
Mailgun::CommunicationError: key not found: :ciphers

### ISSUE THREAD

**Issue by dmc2015** [mailgun/mailgun-ruby#213]
Hello,

I keep getting this error with the ruby gem.

`Mailgun::CommunicationError: key not found: :ciphers`

I am able to run this from curl:

```
curl --user 'api:private_key' -X POST
           https://api.mailgun.net/v4/address/validate
           -F address='foo@mailgun.net'


=> {"message":"Validations are not enabled."}
```

However, it in't working with the gem.

```
.env

ENV['MAILGUN_API_KEY']="private_key-xxxx"
ENV["DOMAIN"]='sandbox_xxxxx.mailgun.org'

mg_client = Mailgun::Client.new ENV['MAILGUN_API_KEY']
    message_params = {from: 'joe@ + ENV["DOMAIN"]',
                      to: user.email,
                      subject: 'Sample Mail using Mailgun API',
                      text: 'This mail is sent using Mailgun API via mailgun-ruby'}

    mg_client.send_message ENV['DOMAIN'], message_params

=> Mailgun::CommunicationError: key not found: :ciphers
from /Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/mailgun-ruby-1.0.3/lib/mailgun.rb:168:in `communication_error'
Caused by KeyError: key not found: :ciphers
from /Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rest-client-1.8.0/lib/restclient/request.rb:163:in `fetch'

```

I tried refrehing my private key in the UI and that didn't help.

**Comment by dmc2015** [comment]
It appears to stem from here:

https://github.com/rest-client/rest-client/blob/92bc04d18499eb20481ee3e3660e382fc377a430/lib/restclient/request.rb#L159

This is using a pretty old version of restclient.


```
unless @ssl_opts.include?(:ciphers)
        # If we're on a Ruby version that has insecure default ciphers,
        # override it with our default list.
        if WeakDefaultCiphers.include?(OpenSSL::SSL::SSLContext::DEFAULT_PARAMS.fetch(:ciphers))
          @ssl_opts[:ciphers] = DefaultCiphers
        end
      end
```


`OpenSSL::SSL::SSLContext::DEFAULT_PARAMS` Does not have a `ciphers` key.

```
OpenSSL::SSL::SSLContext::DEFAULT_PARAMS
=> {:min_version=>769, :verify_mode=>1, :verify_hostname=>true, :options=>2147614804}
```

**Comment by dmc2015** [comment]
My issue was related to the guide that I had followed, the gem they used was outdated, another issue was forgetting the prefix on my domain url. Looks like it sends from my server but still doesn't show up on my mailgun account.
