### ISSUE TITLE
TypeError (no implicit conversion of nil into String)

### ISSUE THREAD

**Issue by canan8** [mailgun/mailgun-ruby#278]
We updated the gem, still get this error.

`mg_client = Mailgun::Client.new mailgun_api, mailgun_api_host`

Then `TypeError` raised on this line:
`mg_client.get("#{mailgun_domain}/events")`

Thanks.

**Comment by Retttro** [comment]
@canan8 I can't reproduce the issue. Tested `mg_client.get("#{mailgun_domain}/events")` and
```
mg_events = Mailgun::Events.new(mg_client, domain)
mg_events.get
```
It didn't raise an error. Could you please share more details(error backtrace, steps to reproduce)?
Thanks!

**Comment by canan8** [comment]
@Retttro sorry for the late response. can you check with these credentials:

```
mailgun_api = "b3669-ad223"
mailgun_api_host = "api.eu.mailgun.net"
mailgun_domain = "mailgun.mymimmobilien.de"
```

Thanks!

**Comment by mykhailoBas** [comment]
There is trace about that in my app
/usr/local/bundle/gems/mailgun-ruby-1.2.8/lib/mailgun/exceptions/exceptions.rb:64:in `+': no implicit conversion of nil into String (TypeError)
/usr/local/bundle/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:249:in `exception_with_response': 401 Unauthorized (RestClient::Unauthorized)

**Comment by canan8** [comment]
@Retttro I updated the version but am still getting the `TypeError` when the credentials are wrong. Can you please confirm?
